### PR TITLE
Update to master

### PR DESCRIPTION
**Pull request by rohanjr**
Merge in master branch, bringing in a few notable changes:
- Terminology changed from "friends" to "followers/following"
- Addition to tests
- SDK upgrade

### CODE REVIEW

**Comment by nemanja-da** [comment]
@rohanjr What changed between PR 74 and this one? Are the changes from 74 in it?

**Comment by cocreature** [comment]
@nemanja-da This is a PR to the `direct-messing` branch that brings it up2date with the current state of master (which includes #74).

**Comment by nemanja-da** [comment]
Thnx for explaining @cocreature 😄Wasn't sure

**Comment by rohanjr** [comment]
@hurryabit I did a second merge after the SDK upgrade was merged to master, to combine it in the same PR.

**Pull request merged**
