### PR TITLE
Remove more stuff related to docker and storybook

### PR DESCRIPTION
**Pull request by hurryabit**
Also remove some other useless files and clean up the package.json file
while we're at removing the storybook stuff from it. And the
`@types/...` depenedencies should definitely go into the
`devDependencies`.

This is part of https://github.com/digital-asset/daml/issues/4866.

---
This change is [Reviewable](https://reviewable.io/reviews/digital-asset/create-daml-app/55)

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
Should .storybook/addons.js  be deleted?

**Comment by shayne-fletcher** [comment]
"@mojotech/json-type-validation": "^3.1.0", got removed. is that right?

**Comment by hurryabit** [comment]
@shayne-fletcher Yes, the whole `.storybook` folder can go. We don't use `json-type-validation` directly here. Only the `@daml/...` libraries use it but they have it as their own dependencies.

**Comment by shayne-fletcher** [comment]
> @shayne-fletcher Yes, the whole `.storybook` folder can go. 

Ok, I point it out because .storybook/addons.js  appears to not be deleted in this PR.

**Comment by rohanjr** [comment]
Nice!

**Comment by hurryabit** [comment]
> Ok, I point it out because .storybook/addons.js appears to not be deleted in this PR.
@shayne-fletcher it got deleted here but since the file was empty before that's a zero line change.

**Pull request merged**
